version: "3.7"

services:
  app:
    build: .
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    env_file: .env
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    networks:
      - app

networks:
  app:
    external:
      name: jsm