version: "3.7"

services:
  app:
    build: .
    image: ${REACT_APP_APP_NAME}:${REACT_APP_APP_VERSION}
    container_name: ${REACT_APP_APP_NAME}
    env_file: .env
    restart: always
    ports:
      - "${REACT_APP_APP_PORT}:${REACT_APP_APP_PORT}"
    volumes:
      - .:/app
    networks:
      - app

networks:
  app:
    external:
      name: jsm
